language: node_js
node_js:
- lts/boron
- node
deploy:
  provider: releases
  api_key:
    secure: Gajsjpb9NOPjIXc89RjzNbYEMiceRgolC6929mvktWxtpMJ2kJo3nsKJHzKgDJvdTHCFxHx+CZJmUADvVKAohnuyS8Hc6rk+ucpvsE9sSA/7YbpK+iraB+dZMnDIIyFErMnKbdrTRpoZf3dbjQJsIy6E09irXlv/QFYZo49S51fO0RkUdjSgoKvJhPpFMmMb8af2D8WQXYfaYQdDKVJf7hGR0wciGg0KJDCt3cVzb/nO2cgqBNSwBbkysIuAfNjuuF0ptMTeYDozSkpAYF5GUcQXEGJrv/oeoFmQc9QGWao9MVc8Nc6YX1xsKcYZseDqph6S5ddeYGqyIyemsi2cmJn0D8ZIikEkLnw7WpM05bHZVPEbNbxGMr4UWBvWQam/IHRyvJlx3Jptv3rrPTK49l8fZm/lUqVJ1nc2x/GU4ctDBttmoBZ18qgbc6SWq4q5Z0C1NbPGgSZod308TNuVOxo8KhxuTtyx0KBoL7phBiiMICP73gPtcX3NzpT3w2OyDBbQCCRIAakDn1GVwaR1x1R4Yf83fOPotW5YGtAgcb/9CIrxUYVMqlae5GPrJ6chkS1mUV+NbGWxKMAJj8cCIE0xWNT8gl2uFmRsMwVEy4SN1SwxYn+4M82Uh63AXChDxeT2N4S6J8h2i1Lil0iIuL1/UDUP3D8g0/1ho3/Vg44=
  file:
    - "html-dangerous-encodings.js"
    - "html-dangerous-encodings.min.js"
  on:
    tags: true
    skip_cleanup: true
