language: node_js
node_js:
  - lts/boron
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TKiaJ/s4y79vMAXBSem1pKiYNJZ+P9WDtfqSrRw3FnHg/QiAv+NeXyl0JVdjYgG5Ejt6dMfbepntKj6HDWVKD3cqteHECprGqAJfg+yqWLip39DMBci2Kaov8sfmnwjCArrx9KaTi3374UjWRTQzL82mE8MbhkBsNNKcTcPbuao/jXqU5aQW+OLc1T2V8Nx80cG3tVMAIlA1go2tOuWv+HrXDPvS3XMjDI81nJTCbZQjRR4MQnxqHeyu7g9uwF8AtWcRMLHL5SvxWrx6aLeegN1U3WjEZuwvSvXWDfpACHy/m57RmOO/SG1b9qPu3tc0Dbn5fbPnrHCWaGRG1e6FQksul+rE58sDnKnalXCbRkgF1sqRtbWZGLiqu97DX0bU0a/0DUlEcpNi5B0Mz1baD39534pvt0Yf2wnyAnn+ZEXZNQJKhRd2+JEQTsLUbC4k+214pn74GD+5u9zyx/FECTAw/MKJ8RrKItt6vMRrf5fBKpBmk9Z9/29qy6jh9xkw/YaLkG8OrS8oPYlzPNfwngs5kcQWtMl4+xpAEOfnijYrBLy/EiNVcLZx1LXFmxbFyWxcu6KYpMi05o44u3VmemWU0MGSQyJptOYtiVG0lhTjsZAKJaggBc2LNBrlI4L4YPzDtOSIiGqoUfmlkNfD3Chh4uMMFsutL0vOm8RKu+c=
  file:
    - 'html-dangerous-encodings.js'
    - 'html-dangerous-encodings.min.js'
  on:
    tags: true
