language: node_js
node_js:
- '4.0'
- '8.0'
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: ARRYmcmduMHT5gCmjuavGhGt+QAQR3zJFGjebzDACW7sp1DwdCCgRhJCj1/L9vj/MJSFu9vjakDccLhL/ll3akG/DzFZgCbf6J44Ogw5MJ9A/ljRfBBJEB+AkJ/VlnBdX3lA44Ag3dv2JzMlE8i9SciLOS0PjOvQywGyXEymlo9zbM3w2O+0Q1UtP4qFgV7mL7suCGCfxWahzGm5lU/OmdCoza5ssuy0RnxOg8OJiw8kzqZLvc3BDrGSSNuoqOkjsitceNBe6yBiTcBtT3PmMb77F2LMV8D65nXoHDhl5RuaNE3+lHCqOFq09jXYNHQHFfyhd7nk2sX9sUC/2hJdnpTfIi0kCjf2FZSZX/QLW0LOyaFbX+OeaIwasghZtFK7f1ucJ8MyYCVZ0xawjyyyhFBrshPtYML5SkINK0aXJ0li24K3wT3toSBh7HgZzhi/tR22KK2O+cpUW0/uMGlnlZ3CxvJPOJUojQztcs/GbJu2PE+teeIaqXE1fTSE5iJuDm9KKGDhgx7eYohyRI1pPXKmwshHgAxtcXzBvimic2mjlf1zohoZi0JqX38tDmSZR1tEm4rExHZlqLXxX4COVDiUkRMuTuNv3IgxA9qDDyHUTiWKV91Faj4mEWF/irRqHKGZrzW0ztaqLZTcM7m1WZg61BxV9nMhuCcMYW25mH4=
    on:
      tags: true
      node: '4.0'
  - provider: releases
    api_key:
      secure: Gajsjpb9NOPjIXc89RjzNbYEMiceRgolC6929mvktWxtpMJ2kJo3nsKJHzKgDJvdTHCFxHx+CZJmUADvVKAohnuyS8Hc6rk+ucpvsE9sSA/7YbpK+iraB+dZMnDIIyFErMnKbdrTRpoZf3dbjQJsIy6E09irXlv/QFYZo49S51fO0RkUdjSgoKvJhPpFMmMb8af2D8WQXYfaYQdDKVJf7hGR0wciGg0KJDCt3cVzb/nO2cgqBNSwBbkysIuAfNjuuF0ptMTeYDozSkpAYF5GUcQXEGJrv/oeoFmQc9QGWao9MVc8Nc6YX1xsKcYZseDqph6S5ddeYGqyIyemsi2cmJn0D8ZIikEkLnw7WpM05bHZVPEbNbxGMr4UWBvWQam/IHRyvJlx3Jptv3rrPTK49l8fZm/lUqVJ1nc2x/GU4ctDBttmoBZ18qgbc6SWq4q5Z0C1NbPGgSZod308TNuVOxo8KhxuTtyx0KBoL7phBiiMICP73gPtcX3NzpT3w2OyDBbQCCRIAakDn1GVwaR1x1R4Yf83fOPotW5YGtAgcb/9CIrxUYVMqlae5GPrJ6chkS1mUV+NbGWxKMAJj8cCIE0xWNT8gl2uFmRsMwVEy4SN1SwxYn+4M82Uh63AXChDxeT2N4S6J8h2i1Lil0iIuL1/UDUP3D8g0/1ho3/Vg44=
    file:
      - "html-dangerous-encodings.js"
      - "html-dangerous-encodings.min.js"
    on:
      tags: true
      node: '8.0'
